name: Regression Test

on:
  push:
    branches:
      - main
      - tugas-regression-test

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: medialend_testing_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Wait for MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

          until mysql -h 127.0.0.1 -uroot -proot -e "SHOW DATABASES;"
          do
            echo "Menunggu MySQL..."
            sleep 5
          done

      - name: sync Database 
        run: node sync-db.js

      - name: Run Tests
        run: npm test